### ISSUE TITLE
运行报错、想问下大佬这是什么原因

### ISSUE THREAD

**Issue by Maccrack** [AntonVanke/JDBrandMember#28]
2021-05-17 17:32:54  INFO  结束运行  Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 343, in main
    check_user()
  File "main.py", line 317, in check_user
    _browser.add_cookie(cookie)
  File "D:\IDE\SDK\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "D:\IDE\SDK\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\IDE\SDK\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid 'expiry'
  (Session info: headless chrome=79.0.3945.117)

**Comment by Hyper-Beast** [comment]
你这浏览器版本太低了，更新看看
