### ISSUE TITLE
为什么会报错，用提3.8和3.95版64位的，难道要用32位的PYTHON吗？我等下用32位试下，不行再来反馈

### ISSUE THREAD

**Issue by lanyucomputer** [AntonVanke/JDBrandMember#37]
2021-05-21 21:33:22  INFO  结束运行  Traceback (most recent call last):
  File "C:\Users\Yang\Desktop\JDBrandMember-main\main.py", line 391, in <module>
    main()
  File "C:\Users\Yang\Desktop\JDBrandMember-main\main.py", line 341, in main
    add_cookie()
  File "C:\Users\Yang\Desktop\JDBrandMember-main\main.py", line 102, in add_cookie
    browser = get_browser(False)
  File "C:\Users\Yang\Desktop\JDBrandMember-main\main.py", line 89, in get_browser
    return webdriver.Chrome(executable_path=get_file_path("drivers/chromedriver"), desired_capabilities={},
  File "C:\Users\Yang\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Yang\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Yang\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Yang\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by lanyucomputer** [comment]
系统是win10 64位

**Comment by lanyucomputer** [comment]
C:\Windows\system32>pip install urllib3
Collecting urllib3
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Installing collected packages: urllib3
Successfully installed urllib3-1.26.4

C:\Windows\system32>pip install webdriver
ERROR: Could not find a version that satisfies the requirement webdriver (from versions: none)
ERROR: No matching distribution found for webdriver

C:\Windows\system32>pip install selenium
Collecting selenium
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Requirement already satisfied: urllib3 in c:\users\yang\appdata\local\programs\python\python39-32\lib\site-packages (from selenium) (1.26.4)
Installing collected packages: selenium
Successfully installed selenium-3.141.0

C:\Windows\system32>系统是win10 64位
'系统是win10' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Windows\system32>
C:\Windows\system32>C:\Users\Yang\AppData\Local\Programs\Python\Python39-32\python.exe C:\Users\Yang\Desktop\JDBrandMember-main\main.py
日志已生成，查看./logs/ Some log data is being generated: ./log/ ...正在关闭，不要退出

C:\Windows\system32>C:\Users\Yang\AppData\Local\Programs\Python\Python39-32\python.exe C:\Users\Yang\Desktop\JDBrandMember-main\main.py
日志已生成，查看./logs/ Some log data is being generated: ./log/ ...正在关闭，不要退出

C:\Windows\system32>

**Comment by AntonVanke** [comment]
你的config配置的`binary`是什么？
