### ISSUE TITLE
UnicodeDecodeError: 出现编码错误'gbk' codec can't decode byte ……

### ISSUE THREAD

**Issue by joshua76y** [AntonVanke/JDBrandMember#44]
Traceback (most recent call last):
  File "D:\python\JDBrandMember-21.05.30\main.py", line 261, in <module>
    CONFIG = yaml.safe_load(open(get_file_path("config.yaml"), "r"))
  File "C:\Program Files\Python39\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Program Files\Python39\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Program Files\Python39\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Program Files\Python39\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Program Files\Python39\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Program Files\Python39\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x87 in position 157: illegal multibyte sequence
2021-05-31 04:08:49  INFO  执行结束

**Comment by AntonVanke** [comment]
哦，一个小错误，我竟然忽略了编码问题
