### ISSUE TITLE
进程异常卡住

### ISSUE THREAD

**Issue by lynn0804** [AntonVanke/JDBrandMember#51]
设置了四个ck
当第一个尝试到10个店铺之后，进程就全部结束了py卡着了
尝试重启也无济于事
![image](https://user-images.githubusercontent.com/52002734/120896670-229a7600-c655-11eb-9938-a1cdb8b6dd5a.png)

**Comment by AntonVanke** [comment]
能否提供一下log文件或截图？
一般位于`logs/jdbm.log`

**Comment by lynn0804** [comment]
![image](https://user-images.githubusercontent.com/52002734/120898209-765c8d80-c65c-11eb-958c-f3c590794a78.png)

**Comment by AntonVanke** [comment]
是否使用了代理？

**Comment by lynn0804** [comment]
clash的rule模式

**Comment by AntonVanke** [comment]
关掉代理尝试一下，我刚刚在我这测试一切正常。
还有一种可能是你的requests库不是要求的版本

**Comment by lynn0804** [comment]
![image](https://user-images.githubusercontent.com/52002734/120899102-9b52ff80-c660-11eb-8297-ac182b8eee03.png)
有可能 等我升级关掉代理重新尝试一下

**Comment by lynn0804** [comment]
很遗憾 我不清楚使我什么地方没有弄好
还是没办法
![Snipaste_2021-06-06_01-11-00](https://user-images.githubusercontent.com/52002734/120899863-5630cc80-c664-11eb-981a-0a70abec64db.png)
![Snipaste_2021-06-06_01-11-48](https://user-images.githubusercontent.com/52002734/120899867-592bbd00-c664-11eb-8a79-07bef5424df6.png)

**Comment by AntonVanke** [comment]
尝试一下最新的，我也不知道是什么情况了

**Comment by lynn0804** [comment]
等明早起来再尝试了  睡了睡了 晚安

**Comment by lynn0804** [comment]
![image](https://user-images.githubusercontent.com/52002734/120911583-1b0db800-c6bb-11eb-81df-26611ac187fd.png)
已经无异常了 即使我现在挂着代理

**Comment by lynn0804** [comment]
![image](https://user-images.githubusercontent.com/52002734/120911636-6d4ed900-c6bb-11eb-8b9f-d36bd5ec653d.png)
有突发问题   我看看

**Comment by lynn0804** [comment]
> ![图像](https://user-images.githubusercontent.com/52002734/120911636-6d4ed900-c6bb-11eb-8b9f-d36bd5ec653d.png)
> 有突发问题我看看

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\lynn\Desktop\JDBrandMember-main\JDBrandMember-main\main.py", line 159, in get_shop_open_card_info
    res = requests.get(url, params=params, headers=get_headers(cookie, host), verify=False)
  File "E:\Python\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\Python\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.m.jd.com', port=443): Max retries exceeded with url: /client.action?appid=jd_shop_member&functionId=getShopOpenCardInfo&body=%7B%22venderId%22%3A%221000147303%22%2C%22channel%22%3A406%7D&client=H5&clientVersion=9.2.0&uuid=88888 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连
接。', None, 10054, None)))



大概率是京东那边断开连接了

**Comment by AntonVanke** [comment]
这看样子还是代理的问题

**Comment by lynn0804** [comment]
> 这看样子还是代理的问题

![image](https://user-images.githubusercontent.com/52002734/120912471-eb15e300-c6c1-11eb-8513-8c52474eaa32.png)
最奇怪的是 我关掉代理尝试重新运行之后又卡住了

**Comment by AntonVanke** [comment]
> > 这看样子还是代理的问题
> 
> ![image](https://user-images.githubusercontent.com/52002734/120912471-eb15e300-c6c1-11eb-8513-8c52474eaa32.png)
> 最奇怪的是 我关掉代理尝试重新运行之后又卡住了

😂好奇怪，我真的不知道为什么了

**Comment by lynn0804** [comment]
今天我把他放到服务器上跑，就没用问题出行了

**Comment by AntonVanke** [comment]
> 今天我把他放到服务器上跑，就没用问题出行了

"就没有问题出现了"？
那应该还是ip的问题

**Comment by lynn0804** [comment]
> > 我每天都要把他服务器上跑，带着问题出行了
> 
> “就没有问题出现了”？
> 那应该还是ip的问题

对 没问题了 尴尬 字都错了
按道理不应该是ip问题 我电脑上都测试过了  
而且我服务器也是海外的ip

**Comment by AntonVanke** [comment]
> > > 我每天都要把他服务器上跑，带着问题出行了
> > 
> > 
> > “就没有问题出现了”？
> > 那应该还是ip的问题
> 
> 对 没问题了 尴尬 字都错了
> 按道理不应该是ip问题 我电脑上都测试过了
> 而且我服务器也是海外的ip

🤣玄学
